#########################################################################
#                                                                       #
#                             OFFENDER SAR COMPLAINT                            #
#                                                                       #
#########################################################################
  offender_sar_complaint:
    name: Offender Subject Access Request Complaint
    permitted_workflows:
      - standard

    permitted_user_roles:
      - responder

    permitted_states:
      - to_be_assessed
      - data_review_required
      - data_to_be_requested
      - waiting_for_data
      - ready_for_vetting
      - vetting_in_progress
      - second_vetting_in_progress
      - ready_to_copy
      - ready_to_dispatch
      - response_required
      - legal_proceedings_ongoing
      - closed
